class Main(object): ...

class A(Main): ...
class B(Main): ...
class C(Main): ...
class D(Main): ...
class E(Main): ...

class X(A, B): ...
class Y(C, D): ...
class Z(C, D, E): ...

class M1(X, Y): ...

# https://en.wikipedia.org/wiki/C3_linearization
# https://en.wikipedia.org/wiki/Multiple_inheritance
print(M1.__mro__)